---
# Copyright 2018, SUSE LINUX GmbH.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# For having the full context, this file should be read
# with the openstack-helm-infra repository, where nodesets
# and jobs are defined.
# NOTE(evrardjp): Some jobs and playbooks haven't been
# migrated to openstack-helm-infra yet.
- project:
    templates:
      - publish-openstack-docs-pti
    check:
      jobs:
        - openstack-helm-lint
        - openstack-helm-dev-deploy-ceph-swift-ovs
        - openstack-helm-dev-deploy-ceph-radosgw-ovs
        - openstack-helm-dev-deploy-ceph-rbd-ovs
        - openstack-helm-dev-deploy-nfs-ovs
        - openstack-helm-dev-deploy-ceph-lb:
            voting: false
        - openstack-helm-dev-deploy-nfs-lb:
            voting: false
        - openstack-helm-dev-deploy-nfs-ldap:
            voting: false
        - openstack-helm-multinode-temp-ubuntu:
            voting: false
        - openstack-helm-ironic-ubuntu:
            voting: false
        - openstack-helm-armada-fullstack-deploy:
            voting: false
        - openstack-helm-kolla-deploy-ceph-ovs
        - openstack-helm-newton-loci-deploy-ceph:
            voting: false
        - openstack-helm-newton-kolla-deploy-ceph:
            voting: false
        - openstack-helm-pike-loci-deploy-ceph:
            voting: false
        - openstack-helm-pike-kolla-deploy-ceph:
            voting: false
    gate:
      jobs:
        - openstack-helm-lint
        - openstack-helm-dev-deploy-ceph-swift-ovs
        - openstack-helm-dev-deploy-ceph-radosgw-ovs
        - openstack-helm-dev-deploy-ceph-rbd-ovs
        - openstack-helm-dev-deploy-nfs-ovs
        - openstack-helm-kolla-deploy-ceph-ovs
    experimental:
      jobs:
        - openstack-helm-multinode-temp-centos
        # NOTE(lamt): Make fedora job experimental until issues with gates are resolved.
        - openstack-helm-multinode-temp-fedora
        - openstack-helm-multinode-temp-tempest
